# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b07ce835015825aeb6fc708a3a925e52adf3f3929b439782d0cdd4990e9c0e92934f6d2ca01b3baea682d78d7708e78bff0bb2fdce478f8d80c14129e13d94

test:
  secret_key_base: ff94a63120112dd3dc30851db04c1cb0d4b4694e73e19fb393e4374216f8bcb4a10ac82b9a9465b30d707b879fc03a95b60e54b901fe283ea4ba0e92347c0a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
